/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tags: Tag;
    media: Media;
    profiles: Profile;
    'learner-profiles': LearnerProfile;
    mentors: Mentor;
    instructors: Instructor;
    cohorts: Cohort;
    applications: Application;
    courses: Course;
    modules: Module;
    lessons: Lesson;
    assignments: Assignment;
    assessments: Assessment;
    submissions: Submission;
    enrollments: Enrollment;
    progress: Progress;
    'journal-entries': JournalEntry;
    sessions: Session;
    'enrollment-attendance': EnrollmentAttendance;
    'pathways-programs': PathwaysProgram;
    'pathways-phases': PathwaysPhase;
    'weekly-experiences': WeeklyExperience;
    'formation-practices': FormationPractice;
    'sermon-series': SermonSery;
    sermons: Sermon;
    'sermons-content': SermonsContent;
    devotionals: Devotional;
    'blog-posts': BlogPost;
    resources: Resource;
    events: Event;
    'prayer-requests': PrayerRequest;
    announcements: Announcement;
    'user-notifications': UserNotification;
    households: Household;
    ministries: Ministry;
    donations: Donation;
    'giving-campaigns': GivingCampaign;
    credentials: Credential;
    'api-keys': ApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'learner-profiles': LearnerProfilesSelect<false> | LearnerProfilesSelect<true>;
    mentors: MentorsSelect<false> | MentorsSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    cohorts: CohortsSelect<false> | CohortsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    assessments: AssessmentsSelect<false> | AssessmentsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    progress: ProgressSelect<false> | ProgressSelect<true>;
    'journal-entries': JournalEntriesSelect<false> | JournalEntriesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'enrollment-attendance': EnrollmentAttendanceSelect<false> | EnrollmentAttendanceSelect<true>;
    'pathways-programs': PathwaysProgramsSelect<false> | PathwaysProgramsSelect<true>;
    'pathways-phases': PathwaysPhasesSelect<false> | PathwaysPhasesSelect<true>;
    'weekly-experiences': WeeklyExperiencesSelect<false> | WeeklyExperiencesSelect<true>;
    'formation-practices': FormationPracticesSelect<false> | FormationPracticesSelect<true>;
    'sermon-series': SermonSeriesSelect<false> | SermonSeriesSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    'sermons-content': SermonsContentSelect<false> | SermonsContentSelect<true>;
    devotionals: DevotionalsSelect<false> | DevotionalsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'user-notifications': UserNotificationsSelect<false> | UserNotificationsSelect<true>;
    households: HouseholdsSelect<false> | HouseholdsSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'giving-campaigns': GivingCampaignsSelect<false> | GivingCampaignsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Auth0 subject (auth0|xxxx)
   */
  auth0Id?: string | null;
  /**
   * Neon Auth user ID (canonical identity)
   */
  neonUserId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  roles: (
    | 'admin'
    | 'pastor'
    | 'leader'
    | 'instructor'
    | 'mentor'
    | 'staff'
    | 'volunteer'
    | 'member'
    | 'student'
    | 'viewer'
  )[];
  /**
   * Canonical human profile (bio, testimony, formation).
   */
  profile?: (number | null) | Profile;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  displayName: string;
  /**
   * Public profile slug
   */
  slug?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  testimony?: string | null;
  /**
   * Primary contact number
   */
  phone?: string | null;
  address?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  preferredContactMethod?: ('email' | 'phone' | 'text') | null;
  /**
   * Honors communication preferences
   */
  doNotContact?: boolean | null;
  emergencyContacts?:
    | {
        fullName: string;
        relationship?: string | null;
        phone: string;
        email?: string | null;
        address?: {
          street1?: string | null;
          street2?: string | null;
          city?: string | null;
          state?: string | null;
          postalCode?: string | null;
          country?: string | null;
        };
        isPrimary?: boolean | null;
        /**
         * Medical, availability, or special instructions
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  pathwaysPhase?: ('restore' | 'root' | 'rise' | 'release' | 'alumni' | 'none') | null;
  pathwaysProgress?: number | null;
  /**
   * Ministries this person actively serves in
   */
  ministries?: (number | Ministry)[] | null;
  /**
   * Calling or area of passion (free text)
   */
  ministryFocus?: string | null;
  volunteerInterests?:
    | ('hospitality' | 'worship' | 'creative' | 'outreach' | 'youth' | 'teaching' | 'prayer' | 'events')[]
    | null;
  spiritualGifts?:
    | (
        | 'teaching'
        | 'leadership'
        | 'wisdom'
        | 'prophecy'
        | 'healing'
        | 'encouragement'
        | 'service'
        | 'administration'
        | 'evangelism'
        | 'faith'
      )[]
    | null;
  skills?: string | null;
  discProfile?: ('d' | 'i' | 's' | 'c') | null;
  enneagram?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') | null;
  spiritualGiftAssessment?: string | null;
  badges?:
    | {
        title?: string | null;
        icon?: (number | null) | Media;
        earnedDate?: string | null;
        id?: string | null;
      }[]
    | null;
  isMentorCandidate?: boolean | null;
  leadershipTrackStatus?: ('none' | 'training' | 'serving' | 'leading') | null;
  leadershipNotes?: string | null;
  accountabilityPartner?: (number | null) | Profile;
  accountabilityNotes?: string | null;
  pastorOrMinistryLead?: (number | null) | Profile;
  leaderNotes?: string | null;
  /**
   * Primary household this person belongs to
   */
  household?: (number | null) | Household;
  householdRole?: ('head' | 'spouse' | 'adult' | 'youth' | 'child') | null;
  emergencyContactNotes?: string | null;
  /**
   * Self-reported tithing status (no amounts)
   */
  isTither?: ('yes' | 'growing' | 'no' | 'unspecified') | null;
  givingFrequency?: ('weekly' | 'biweekly' | 'monthly' | 'seasonal' | 'special') | null;
  givingMethod?: ('in_person' | 'online' | 'text' | 'recurring')[] | null;
  participatesInCampaigns?: boolean | null;
  /**
   * Pastoral or stewardship notes (private)
   */
  givingNotes?: string | null;
  /**
   * Last recorded giving activity (optional)
   */
  lastGaveAt?: string | null;
  /**
   * e.g. Tithe, Missions, Building Fund
   */
  preferredGivingFund?: string | null;
  /**
   * Linked donation records (if enabled)
   */
  donations?: (number | Donation)[] | null;
  user?: (number | null) | User;
  /**
   * Indicative roles only. Actual permissions come from Users.
   */
  roles?:
    | (
        | 'admin'
        | 'pastor'
        | 'leader'
        | 'instructor'
        | 'mentor'
        | 'staff'
        | 'volunteer'
        | 'member'
        | 'student'
        | 'viewer'
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Sermon;
    canonicalURL?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  visibility?: ('public' | 'private') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  title: string;
  description?: string | null;
  leader?: (number | null) | Profile;
  teamMembers?: (number | Profile)[] | null;
  status?: ('active' | 'seasonal' | 'paused') | null;
  meetingSchedule?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households".
 */
export interface Household {
  id: number;
  /**
   * e.g. The Johnson Family
   */
  name: string;
  members?: (number | Profile)[] | null;
  primaryContact?: (number | null) | Profile;
  campus?: string | null;
  isActive?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  donor: number | Profile;
  amount?: number | null;
  /**
   * e.g. Tithe, Missions, Building Fund
   */
  fund?: string | null;
  method?: ('online' | 'text' | 'in_person' | 'check') | null;
  date: string;
  reference?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learner-profiles".
 */
export interface LearnerProfile {
  id: number;
  profile: number | Profile;
  enrolledCourses?: (number | Course)[] | null;
  activePathways?: (number | PathwaysProgram)[] | null;
  credentialsEarned?: (number | Credential)[] | null;
  learningGoals?: string | null;
  /**
   * Internal learning notes (not visible to learner by default).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug?: string | null;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  courseType: 'biblical' | 'theology' | 'leadership' | 'formation' | 'life-skills' | 'ministry' | 'vocational';
  level?: ('intro' | 'intermediate' | 'advanced') | null;
  format?: ('self-paced' | 'cohort' | 'hybrid') | null;
  estimatedDuration?: {
    weeks?: number | null;
    hours?: number | null;
  };
  learningObjectives?:
    | {
        objective: string;
        id?: string | null;
      }[]
    | null;
  modules?: (number | Module)[] | null;
  prerequisites?: (number | Course)[] | null;
  instructors?: (number | Instructor)[] | null;
  credentials?: (number | Credential)[] | null;
  /**
   * Mark if this course is required or optional in a Pathways program.
   */
  usedInPathways?: boolean | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  featuredImage?: (number | null) | Media;
  resources?: (number | Resource)[] | null;
  courseState?: ('active' | 'inactive' | 'archived') | null;
  publishedAt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Controls the order of modules within a course.
   */
  order: number;
  course: number | Course;
  /**
   * Lessons contained within this module.
   */
  lessons?: (number | Lesson)[] | null;
  learningObjectives?:
    | {
        objective: string;
        id?: string | null;
      }[]
    | null;
  unlockType?: ('sequential' | 'date' | 'manual' | 'open') | null;
  unlockDate?: string | null;
  /**
   * Roles allowed to manually unlock this module for learners.
   */
  manualUnlockRoles?: ('admin' | 'pastor' | 'leader' | 'instructor')[] | null;
  /**
   * Indicates this module is used within a Pathways phase.
   */
  usedInPathways?: boolean | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  visibility?: ('public' | 'enrolled' | 'cohort') | null;
  moduleState?: ('active' | 'archived') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  summary?: string | null;
  /**
   * Controls lesson order within the module.
   */
  order: number;
  module: number | Module;
  lessonType: 'video' | 'reading' | 'devotional' | 'discussion' | 'assignment' | 'assessment' | 'practice';
  /**
   * Primary lesson content (text, scripture, images, embeds).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: {
    video?: (number | null) | Media;
    audio?: (number | null) | Media;
  };
  scriptureFocus?:
    | {
        reference: string;
        translation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Prompt for journaling or personal reflection.
   */
  reflectionPrompt?: string | null;
  /**
   * Estimated completion time in minutes.
   */
  estimatedTime?: number | null;
  /**
   * Must this lesson be completed to progress?
   */
  completionRequired?: boolean | null;
  assignment?: (number | null) | Assignment;
  assessment?: (number | null) | Assessment;
  /**
   * Controls what mentors can see for this lesson.
   */
  mentorVisibility?: ('summary' | 'full' | 'reflection') | null;
  usedInPathways?: boolean | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  visibility?: ('public' | 'enrolled' | 'cohort') | null;
  lessonState?: ('active' | 'archived') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: number;
  title: string;
  /**
   * Full assignment instructions visible to learners.
   */
  instructions: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  lesson: number | Lesson;
  assignmentType: 'reflection' | 'short-answer' | 'essay' | 'project' | 'discussion' | 'practice' | 'file';
  submissionType?: ('text' | 'file' | 'link' | 'mixed') | null;
  allowMultipleSubmissions?: boolean | null;
  dueType?: ('none' | 'fixed' | 'relative') | null;
  dueDate?: string | null;
  dueAfterDays?: number | null;
  gradingType?: ('completion' | 'pass-fail' | 'scored') | null;
  passingScore?: number | null;
  rubric?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mentorFeedbackEnabled?: boolean | null;
  usedInPathways?: boolean | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  status?: ('draft' | 'active' | 'archived' | 'published') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways-phases".
 */
export interface PathwaysPhase {
  id: number;
  /**
   * Example: "Phase 1 – Restore"
   */
  title: string;
  /**
   * Controls progression order within the program.
   */
  order: number;
  program: number | PathwaysProgram;
  /**
   * Theme word or phrase (e.g. Healing, Identity, Calling).
   */
  theme?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requiredCourses?: (number | Course)[] | null;
  requiredModules?: (number | Module)[] | null;
  requiredLessons?: (number | Lesson)[] | null;
  requiredAssignments?: (number | Assignment)[] | null;
  requiredAssessments?: (number | Assessment)[] | null;
  formationPractices?:
    | {
        practice: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  completionRule?: ('all-required' | 'percentage' | 'mentor-approval') | null;
  requiredCompletionPercentage?: number | null;
  mentorReviewRequired?: boolean | null;
  pastorApprovalRequired?: boolean | null;
  status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways-programs".
 */
export interface PathwaysProgram {
  id: number;
  /**
   * Example: "Pathways Discipleship Journey"
   */
  title: string;
  /**
   * URL-safe identifier (manual or generated).
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  targetAudience?: ('new-believers' | 'members' | 'leaders' | 'ministry' | 'general')[] | null;
  /**
   * Spiritual intent of this program (formation goal, not curriculum).
   */
  spiritualFocus?: string | null;
  /**
   * Ordered phases that make up this Pathways program.
   */
  phases?: (number | PathwaysPhase)[] | null;
  estimatedDurationWeeks?: number | null;
  /**
   * If enabled, users must be enrolled to participate.
   */
  requiresEnrollment?: boolean | null;
  requiresMentor?: boolean | null;
  status?: ('draft' | 'active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments".
 */
export interface Assessment {
  id: number;
  title: string;
  /**
   * Instructions or overview shown before the assessment begins.
   */
  description?: string | null;
  lesson: number | Lesson;
  assessmentType: 'quiz' | 'exam' | 'scripture' | 'review';
  /**
   * Optional time limit (minutes). Leave blank for untimed.
   */
  timeLimitMinutes?: number | null;
  allowRetakes?: boolean | null;
  maxAttempts?: number | null;
  passingScore?: number | null;
  questions: {
    questionText: string;
    questionType: 'multiple-choice' | 'true-false' | 'short-answer' | 'scripture';
    options?:
      | {
          optionText: string;
          isCorrect?: boolean | null;
          id?: string | null;
        }[]
      | null;
    correctAnswer?: string | null;
    points?: number | null;
    id?: string | null;
  }[];
  usedInPathways?: boolean | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  status?: ('draft' | 'active' | 'archived' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  profile: number | Profile;
  coursesTaught?: (number | Course)[] | null;
  credentials?: (number | Credential)[] | null;
  instructorNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  /**
   * Example: "Pathways Leadership Certificate" or "Ministry Foundations Credential".
   */
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credentialType: 'certificate' | 'ministry' | 'leadership' | 'badge';
  issuingBody?: ('commons' | 'pathways' | 'fcf') | null;
  requiredCourses?: (number | Course)[] | null;
  requiredPathwaysProgram?: (number | null) | PathwaysProgram;
  requiredPathwaysPhase?: (number | null) | PathwaysPhase;
  requiredAssignments?: (number | Assignment)[] | null;
  requiredAssessments?: (number | Assessment)[] | null;
  /**
   * Optional minimum assessment score required.
   */
  minimumScore?: number | null;
  mentorApprovalRequired?: boolean | null;
  /**
   * If enabled, credential is automatically awarded when requirements are met.
   */
  autoAward?: boolean | null;
  requiresPastorApproval?: boolean | null;
  /**
   * Optional certificate PDF or image template.
   */
  certificateTemplate?: (number | null) | Media;
  expires?: boolean | null;
  expirationMonths?: number | null;
  visibility?: ('public' | 'internal' | 'private') | null;
  status?: ('draft' | 'active' | 'archived' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  description?: string | null;
  resourceType: 'document' | 'audio' | 'video' | 'image' | 'link' | 'devotional';
  file?: (number | null) | Media;
  externalUrl?: string | null;
  categories?:
    | ('sermons' | 'bible-study' | 'prayer' | 'devotional' | 'leadership' | 'youth' | 'outreach' | 'general')[]
    | null;
  relatedCourses?: (number | Course)[] | null;
  relatedPathwaysPhases?: (number | PathwaysPhase)[] | null;
  relatedMinistries?: ('worship' | 'youth' | 'outreach' | 'media' | 'prayer')[] | null;
  visibility?: ('public' | 'members' | 'leaders' | 'private') | null;
  status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors".
 */
export interface Mentor {
  id: number;
  profile: number | Profile;
  assignedCohorts?: (number | Cohort)[] | null;
  /**
   * Profiles this mentor is directly responsible for.
   */
  assignedLearners?: (number | Profile)[] | null;
  availability?: ('limited' | 'moderate' | 'open') | null;
  mentorNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts".
 */
export interface Cohort {
  id: number;
  /**
   * Example: "Pathways Leadership – Fall 2026 (Cohort A)"
   */
  name: string;
  description?: string | null;
  pathwaysProgram: number | PathwaysProgram;
  pathwaysPhase: number | PathwaysPhase;
  startDate: string;
  endDate?: string | null;
  /**
   * Example: "Sundays at 10:30am (in person)" or "Tuesdays on Zoom"
   */
  meetingSchedule?: string | null;
  /**
   * Assigned mentors/coaches for this cohort.
   */
  mentors?: (number | User)[] | null;
  /**
   * Facilitators or instructors guiding sessions.
   */
  facilitators?: (number | User)[] | null;
  /**
   * Participants enrolled in this cohort.
   */
  members?: (number | User)[] | null;
  /**
   * Optional: courses this cohort focuses on (overrides default Pathways mapping).
   */
  courses?: (number | Course)[] | null;
  /**
   * Optional: specific modules emphasized for this cohort.
   */
  modules?: (number | Module)[] | null;
  visibility?: ('private' | 'members' | 'public') | null;
  cohortStatus?: ('planned' | 'active' | 'completed' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  fullName: string;
  preferredName?: string | null;
  dateOfBirth?: string | null;
  gender?: ('male' | 'female' | 'nonbinary' | 'prefer-not') | null;
  phone: string;
  email: string;
  address?: string | null;
  fwcMember?: ('yes' | 'attend' | 'interested' | 'other-church') | null;
  churchName?: string | null;
  previousPrograms?: ('yes' | 'no') | null;
  previousProgramsDescription?: string | null;
  phase: 'restore' | 'root' | 'rise' | 'release' | 'unsure';
  whyJoin?: string | null;
  spiritualGoals?: string | null;
  preferredMeetingTime: 'weeknights' | 'saturday' | 'sunday' | 'any';
  meetingFrequency: 'weekly' | 'biweekly' | 'monthly' | 'unsure';
  supportNeeds?: ('virtual' | 'accessibility' | 'other')[] | null;
  otherSupport?: string | null;
  agreement: boolean;
  signature: string;
  signatureDate: string;
  status: 'pending' | 'interview' | 'accepted' | 'waitlisted' | 'rejected';
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  profile: number | Profile;
  assignment: number | Assignment;
  lesson: number | Lesson;
  assignmentTitle?: string | null;
  textEntry?: string | null;
  attachments?: (number | Media)[] | null;
  status?: ('submitted' | 'reviewed' | 'revise' | 'passed' | 'failed') | null;
  grade?: string | null;
  feedback?: string | null;
  submittedAt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  course: number | Course;
  courseTitle?: string | null;
  /**
   * Canonical person profile being enrolled.
   */
  profile: number | Profile;
  /**
   * Linked learner profile (optional but recommended).
   */
  learnerProfile?: (number | null) | LearnerProfile;
  /**
   * Primary instructor for this enrollment.
   */
  instructor?: (number | null) | Profile;
  /**
   * Assigned mentor or coach for formation support.
   */
  mentor?: (number | null) | Profile;
  cohort?: (number | null) | Cohort;
  pathwaysProgram?: (number | null) | PathwaysProgram;
  pathwaysPhase?: (number | null) | PathwaysPhase;
  status?: ('enrolled' | 'in-progress' | 'completed' | 'withdrawn' | 'incomplete') | null;
  /**
   * High-level progress indicator (detail lives in Progress collection).
   */
  progress?: number | null;
  certificateIssued?: boolean | null;
  startDate: string;
  endDate?: string | null;
  /**
   * Administrative or pastoral notes about this enrollment.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress".
 */
export interface Progress {
  id: number;
  user: number | User;
  course?: (number | null) | Course;
  module?: (number | null) | Module;
  lesson?: (number | null) | Lesson;
  assignment?: (number | null) | Assignment;
  assessment?: (number | null) | Assessment;
  pathwaysProgram?: (number | null) | PathwaysProgram;
  pathwaysPhase?: (number | null) | PathwaysPhase;
  status: 'not-started' | 'in-progress' | 'completed' | 'submitted' | 'passed' | 'failed';
  startedAt?: string | null;
  completedAt?: string | null;
  score?: number | null;
  attempts?: number | null;
  submission?: {
    textResponse?: string | null;
    file?: (number | null) | Media;
    externalLink?: string | null;
    submittedAt?: string | null;
  };
  feedback?: {
    comment?: string | null;
    reviewedBy?: (number | null) | User;
    reviewedAt?: string | null;
  };
  /**
   * Optional linked journal entry for reflection-based lessons.
   */
  reflectionEntry?: (number | null) | JournalEntry;
  /**
   * Prevents further changes (used after final review).
   */
  isLocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-entries".
 */
export interface JournalEntry {
  id: number;
  user: number | User;
  /**
   * Short title for the reflection (e.g., "Week 2 Reflection" or "James 2:1–11").
   */
  title: string;
  /**
   * Optional prompt that the learner is responding to (lesson prompt / mentor prompt).
   */
  prompt?: string | null;
  entry: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  lesson?: (number | null) | Lesson;
  assignment?: (number | null) | Assignment;
  course?: (number | null) | Course;
  module?: (number | null) | Module;
  pathwaysProgram?: (number | null) | PathwaysProgram;
  pathwaysPhase?: (number | null) | PathwaysPhase;
  /**
   * If this reflection is tied to a specific cohort/group.
   */
  cohort?: (number | null) | Cohort;
  /**
   * Optional: link to the Progress record this reflection supports.
   */
  progressRecord?: (number | null) | Progress;
  /**
   * Controls who can view this entry. Private is safest by default.
   */
  visibility: 'private' | 'mentor' | 'cohort' | 'public';
  feedback?: {
    mentorComment?: string | null;
    reviewStatus?: ('not-reviewed' | 'reviewed' | 'needs-follow-up') | null;
    reviewedBy?: (number | null) | User;
    reviewedAt?: string | null;
  };
  entryStatus?: ('active' | 'flagged' | 'archived') | null;
  flagReason?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  title: string;
  description?: string | null;
  sessionType: 'course' | 'cohort' | 'weekly-experience' | 'workshop';
  course?: (number | null) | Course;
  cohort?: (number | null) | Cohort;
  weeklyExperience?: (number | null) | WeeklyExperience;
  startDateTime: string;
  endDateTime?: string | null;
  deliveryMode?: ('in-person' | 'virtual' | 'hybrid') | null;
  location?: string | null;
  virtualLink?: string | null;
  facilitators?: (number | Profile)[] | null;
  /**
   * If false, attendance will not affect progress.
   */
  attendanceRequired?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-experiences".
 */
export interface WeeklyExperience {
  id: number;
  /**
   * Example: "Week 3 – Healing the Inner Self"
   */
  title: string;
  weekNumber: number;
  pathwaysPhase: number | PathwaysPhase;
  /**
   * Weekly theme or focus word (e.g. Identity, Healing, Calling).
   */
  theme?: string | null;
  scriptureFocus?:
    | {
        reference: string;
        translation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Teaching, devotional content, or weekly lesson.
   */
  teachingContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedLessons?: (number | Lesson)[] | null;
  /**
   * Practices participants should engage this week.
   */
  formationPractices?: (number | FormationPractice)[] | null;
  reflectionQuestions?:
    | {
        question: string;
        id?: string | null;
      }[]
    | null;
  journalRequired?: boolean | null;
  /**
   * Cohort or small-group activity for this week.
   */
  groupActivity?: string | null;
  /**
   * Private notes or guidance for mentors facilitating this week.
   */
  mentorGuidance?: string | null;
  completionRequired?: boolean | null;
  estimatedTimeMinutes?: number | null;
  status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formation-practices".
 */
export interface FormationPractice {
  id: number;
  /**
   * Example: Prayer, Fasting, Sankofa Reflection
   */
  title: string;
  /**
   * Optional URL-safe identifier.
   */
  slug?: string | null;
  practiceType: 'spiritual' | 'embodied' | 'communal' | 'justice' | 'reflective';
  /**
   * What this practice is and why it matters spiritually.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How to practice this (step-by-step or guided).
   */
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  scriptureReferences?:
    | {
        reference: string;
        translation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional theological framing or pastoral note.
   */
  theologicalReflection?: string | null;
  suggestedJournalPrompt?: string | null;
  requiresJournalEntry?: boolean | null;
  usedInPathways?: boolean | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollment-attendance".
 */
export interface EnrollmentAttendance {
  id: number;
  enrollment: number | Enrollment;
  session: number | Session;
  profile: number | Profile;
  attendanceStatus: 'present' | 'late' | 'excused' | 'absent';
  attendanceMode?: ('in-person' | 'virtual') | null;
  recordedBy?: (number | null) | User;
  recordedAt?: string | null;
  /**
   * Pastoral or instructional context for this record.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermon-series".
 */
export interface SermonSery {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Sermon;
  seo?: {
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Sermon;
      canonicalURL?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons-content".
 */
export interface SermonsContent {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Only users with the "pastor" role appear here.
   */
  pastor: number | User;
  series?: (number | null) | SermonSery;
  scripture?: string | null;
  tags?: (number | Tag)[] | null;
  audio?: (number | null) | Sermon;
  video?: (number | null) | Sermon;
  slides?: (number | null) | Sermon;
  transcript?: (number | null) | Sermon;
  duration?: string | null;
  date: string;
  campus: 'clarksville' | 'murfreesboro' | 'nashville' | 'online';
  /**
   * Upload sermon notes (PDF, DOCX, images, etc.)
   */
  notes?: (number | null) | Sermon;
  /**
   * Recommended sermons to show after watching.
   */
  recommended?: (number | SermonsContent)[] | null;
  status?: ('draft' | 'review' | 'published') | null;
  seo?: {
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Sermon;
      canonicalURL?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devotionals".
 */
export interface Devotional {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Primary scripture reference
   */
  scripture?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional prompt for journaling or reflection.
   */
  reflectionPrompt?: string | null;
  author?: (number | null) | User;
  date: string;
  formationPractices?: (number | FormationPractice)[] | null;
  pathwaysPhases?: (number | PathwaysPhase)[] | null;
  relatedResources?: (number | Resource)[] | null;
  visibility?: ('public' | 'members' | 'leaders') | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Sermon;
    canonicalURL?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug?: string | null;
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Sermon;
    canonicalURL?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: string | null;
  eventType: 'church' | 'prayer-call' | 'workshop' | 'retreat' | 'service';
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  virtualLink?: string | null;
  facilitators?: (number | Profile)[] | null;
  /**
   * Theme, scripture, or intention for prayer calls.
   */
  spiritualFocus?: string | null;
  /**
   * Optional prayer requests to highlight.
   */
  relatedPrayerRequests?: (number | PrayerRequest)[] | null;
  /**
   * If checked, a Session should be created for attendance.
   */
  requiresSession?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  /**
   * Person submitting the prayer request.
   */
  profile: number | Profile;
  /**
   * Short summary (shown in lists).
   */
  summary: string;
  /**
   * Full prayer request details.
   */
  request: string;
  visibility: 'private' | 'leaders' | 'prayer-team' | 'public';
  /**
   * May leaders/prayer team follow up?
   */
  allowFollowUp?: boolean | null;
  status?: ('active' | 'answered' | 'ongoing' | 'closed') | null;
  /**
   * Optional testimony when prayer is answered.
   */
  answerTestimony?: string | null;
  answeredAt?: string | null;
  /**
   * Optional prayer call or gathering connected to this request.
   */
  relatedEvent?: (number | null) | Event;
  /**
   * Leader or pastor assigned for follow-up.
   */
  assignedLeader?: (number | null) | Profile;
  /**
   * Internal pastoral notes (leaders only).
   */
  followUpNotes?: string | null;
  followUpDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  message: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  audience: ('all' | 'members' | 'leaders' | 'learners' | 'mentors' | 'instructors')[];
  relatedMinistries?: ('worship' | 'youth' | 'outreach' | 'prayer' | 'media')[] | null;
  relatedCourse?: (number | null) | Course;
  relatedPathwayPhase?: (number | null) | PathwaysPhase;
  displayLocations?: ('homepage' | 'church-dashboard' | 'lms-dashboard' | 'pathways' | 'email')[] | null;
  startDate?: string | null;
  endDate?: string | null;
  status?: ('active' | 'scheduled' | 'expired' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notifications".
 */
export interface UserNotification {
  id: number;
  user: number | User;
  title: string;
  message: string;
  notificationType: 'announcement' | 'pathways' | 'lms' | 'credential' | 'mentor' | 'system';
  announcement?: (number | null) | Announcement;
  resource?: (number | null) | Resource;
  course?: (number | null) | Course;
  pathwaysProgram?: (number | null) | PathwaysProgram;
  pathwaysPhase?: (number | null) | PathwaysPhase;
  enrollment?: (number | null) | Enrollment;
  credential?: (number | null) | Credential;
  read?: boolean | null;
  /**
   * Timestamp when the user opened the notification.
   */
  readAt?: string | null;
  deliveryChannels?: ('in-app' | 'email' | 'push' | 'sms')[] | null;
  /**
   * Optional expiration (notification auto-hidden after this date).
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "giving-campaigns".
 */
export interface GivingCampaign {
  id: number;
  title: string;
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  donations?: (number | Donation)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  label: string;
  key: string;
  apiTags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'learner-profiles';
        value: number | LearnerProfile;
      } | null)
    | ({
        relationTo: 'mentors';
        value: number | Mentor;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'cohorts';
        value: number | Cohort;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'assignments';
        value: number | Assignment;
      } | null)
    | ({
        relationTo: 'assessments';
        value: number | Assessment;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'progress';
        value: number | Progress;
      } | null)
    | ({
        relationTo: 'journal-entries';
        value: number | JournalEntry;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'enrollment-attendance';
        value: number | EnrollmentAttendance;
      } | null)
    | ({
        relationTo: 'pathways-programs';
        value: number | PathwaysProgram;
      } | null)
    | ({
        relationTo: 'pathways-phases';
        value: number | PathwaysPhase;
      } | null)
    | ({
        relationTo: 'weekly-experiences';
        value: number | WeeklyExperience;
      } | null)
    | ({
        relationTo: 'formation-practices';
        value: number | FormationPractice;
      } | null)
    | ({
        relationTo: 'sermon-series';
        value: number | SermonSery;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'sermons-content';
        value: number | SermonsContent;
      } | null)
    | ({
        relationTo: 'devotionals';
        value: number | Devotional;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'user-notifications';
        value: number | UserNotification;
      } | null)
    | ({
        relationTo: 'households';
        value: number | Household;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'giving-campaigns';
        value: number | GivingCampaign;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  auth0Id?: T;
  neonUserId?: T;
  firstName?: T;
  lastName?: T;
  roles?: T;
  profile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  avatar?: T;
  bio?: T;
  testimony?: T;
  phone?: T;
  address?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  preferredContactMethod?: T;
  doNotContact?: T;
  emergencyContacts?:
    | T
    | {
        fullName?: T;
        relationship?: T;
        phone?: T;
        email?: T;
        address?:
          | T
          | {
              street1?: T;
              street2?: T;
              city?: T;
              state?: T;
              postalCode?: T;
              country?: T;
            };
        isPrimary?: T;
        notes?: T;
        id?: T;
      };
  pathwaysPhase?: T;
  pathwaysProgress?: T;
  ministries?: T;
  ministryFocus?: T;
  volunteerInterests?: T;
  spiritualGifts?: T;
  skills?: T;
  discProfile?: T;
  enneagram?: T;
  spiritualGiftAssessment?: T;
  badges?:
    | T
    | {
        title?: T;
        icon?: T;
        earnedDate?: T;
        id?: T;
      };
  isMentorCandidate?: T;
  leadershipTrackStatus?: T;
  leadershipNotes?: T;
  accountabilityPartner?: T;
  accountabilityNotes?: T;
  pastorOrMinistryLead?: T;
  leaderNotes?: T;
  household?: T;
  householdRole?: T;
  emergencyContactNotes?: T;
  isTither?: T;
  givingFrequency?: T;
  givingMethod?: T;
  participatesInCampaigns?: T;
  givingNotes?: T;
  lastGaveAt?: T;
  preferredGivingFund?: T;
  donations?: T;
  user?: T;
  roles?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learner-profiles_select".
 */
export interface LearnerProfilesSelect<T extends boolean = true> {
  profile?: T;
  enrolledCourses?: T;
  activePathways?: T;
  credentialsEarned?: T;
  learningGoals?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors_select".
 */
export interface MentorsSelect<T extends boolean = true> {
  profile?: T;
  assignedCohorts?: T;
  assignedLearners?: T;
  availability?: T;
  mentorNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  profile?: T;
  coursesTaught?: T;
  credentials?: T;
  instructorNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts_select".
 */
export interface CohortsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  pathwaysProgram?: T;
  pathwaysPhase?: T;
  startDate?: T;
  endDate?: T;
  meetingSchedule?: T;
  mentors?: T;
  facilitators?: T;
  members?: T;
  courses?: T;
  modules?: T;
  visibility?: T;
  cohortStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  preferredName?: T;
  dateOfBirth?: T;
  gender?: T;
  phone?: T;
  email?: T;
  address?: T;
  fwcMember?: T;
  churchName?: T;
  previousPrograms?: T;
  previousProgramsDescription?: T;
  phase?: T;
  whyJoin?: T;
  spiritualGoals?: T;
  preferredMeetingTime?: T;
  meetingFrequency?: T;
  supportNeeds?: T;
  otherSupport?: T;
  agreement?: T;
  signature?: T;
  signatureDate?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  courseType?: T;
  level?: T;
  format?: T;
  estimatedDuration?:
    | T
    | {
        weeks?: T;
        hours?: T;
      };
  learningObjectives?:
    | T
    | {
        objective?: T;
        id?: T;
      };
  modules?: T;
  prerequisites?: T;
  instructors?: T;
  credentials?: T;
  usedInPathways?: T;
  pathwaysPhases?: T;
  featuredImage?: T;
  resources?: T;
  courseState?: T;
  publishedAt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  overview?: T;
  order?: T;
  course?: T;
  lessons?: T;
  learningObjectives?:
    | T
    | {
        objective?: T;
        id?: T;
      };
  unlockType?: T;
  unlockDate?: T;
  manualUnlockRoles?: T;
  usedInPathways?: T;
  pathwaysPhases?: T;
  visibility?: T;
  moduleState?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  order?: T;
  module?: T;
  lessonType?: T;
  content?: T;
  media?:
    | T
    | {
        video?: T;
        audio?: T;
      };
  scriptureFocus?:
    | T
    | {
        reference?: T;
        translation?: T;
        id?: T;
      };
  reflectionPrompt?: T;
  estimatedTime?: T;
  completionRequired?: T;
  assignment?: T;
  assessment?: T;
  mentorVisibility?: T;
  usedInPathways?: T;
  pathwaysPhases?: T;
  visibility?: T;
  lessonState?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  title?: T;
  instructions?: T;
  lesson?: T;
  assignmentType?: T;
  submissionType?: T;
  allowMultipleSubmissions?: T;
  dueType?: T;
  dueDate?: T;
  dueAfterDays?: T;
  gradingType?: T;
  passingScore?: T;
  rubric?: T;
  mentorFeedbackEnabled?: T;
  usedInPathways?: T;
  pathwaysPhases?: T;
  status?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments_select".
 */
export interface AssessmentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lesson?: T;
  assessmentType?: T;
  timeLimitMinutes?: T;
  allowRetakes?: T;
  maxAttempts?: T;
  passingScore?: T;
  questions?:
    | T
    | {
        questionText?: T;
        questionType?: T;
        options?:
          | T
          | {
              optionText?: T;
              isCorrect?: T;
              id?: T;
            };
        correctAnswer?: T;
        points?: T;
        id?: T;
      };
  usedInPathways?: T;
  pathwaysPhases?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  profile?: T;
  assignment?: T;
  lesson?: T;
  assignmentTitle?: T;
  textEntry?: T;
  attachments?: T;
  status?: T;
  grade?: T;
  feedback?: T;
  submittedAt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  course?: T;
  courseTitle?: T;
  profile?: T;
  learnerProfile?: T;
  instructor?: T;
  mentor?: T;
  cohort?: T;
  pathwaysProgram?: T;
  pathwaysPhase?: T;
  status?: T;
  progress?: T;
  certificateIssued?: T;
  startDate?: T;
  endDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress_select".
 */
export interface ProgressSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  module?: T;
  lesson?: T;
  assignment?: T;
  assessment?: T;
  pathwaysProgram?: T;
  pathwaysPhase?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  score?: T;
  attempts?: T;
  submission?:
    | T
    | {
        textResponse?: T;
        file?: T;
        externalLink?: T;
        submittedAt?: T;
      };
  feedback?:
    | T
    | {
        comment?: T;
        reviewedBy?: T;
        reviewedAt?: T;
      };
  reflectionEntry?: T;
  isLocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-entries_select".
 */
export interface JournalEntriesSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  prompt?: T;
  entry?: T;
  lesson?: T;
  assignment?: T;
  course?: T;
  module?: T;
  pathwaysProgram?: T;
  pathwaysPhase?: T;
  cohort?: T;
  progressRecord?: T;
  visibility?: T;
  feedback?:
    | T
    | {
        mentorComment?: T;
        reviewStatus?: T;
        reviewedBy?: T;
        reviewedAt?: T;
      };
  entryStatus?: T;
  flagReason?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  sessionType?: T;
  course?: T;
  cohort?: T;
  weeklyExperience?: T;
  startDateTime?: T;
  endDateTime?: T;
  deliveryMode?: T;
  location?: T;
  virtualLink?: T;
  facilitators?: T;
  attendanceRequired?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollment-attendance_select".
 */
export interface EnrollmentAttendanceSelect<T extends boolean = true> {
  enrollment?: T;
  session?: T;
  profile?: T;
  attendanceStatus?: T;
  attendanceMode?: T;
  recordedBy?: T;
  recordedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways-programs_select".
 */
export interface PathwaysProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  targetAudience?: T;
  spiritualFocus?: T;
  phases?: T;
  estimatedDurationWeeks?: T;
  requiresEnrollment?: T;
  requiresMentor?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways-phases_select".
 */
export interface PathwaysPhasesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  program?: T;
  theme?: T;
  description?: T;
  requiredCourses?: T;
  requiredModules?: T;
  requiredLessons?: T;
  requiredAssignments?: T;
  requiredAssessments?: T;
  formationPractices?:
    | T
    | {
        practice?: T;
        description?: T;
        id?: T;
      };
  completionRule?: T;
  requiredCompletionPercentage?: T;
  mentorReviewRequired?: T;
  pastorApprovalRequired?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-experiences_select".
 */
export interface WeeklyExperiencesSelect<T extends boolean = true> {
  title?: T;
  weekNumber?: T;
  pathwaysPhase?: T;
  theme?: T;
  scriptureFocus?:
    | T
    | {
        reference?: T;
        translation?: T;
        id?: T;
      };
  teachingContent?: T;
  relatedLessons?: T;
  formationPractices?: T;
  reflectionQuestions?:
    | T
    | {
        question?: T;
        id?: T;
      };
  journalRequired?: T;
  groupActivity?: T;
  mentorGuidance?: T;
  completionRequired?: T;
  estimatedTimeMinutes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formation-practices_select".
 */
export interface FormationPracticesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  practiceType?: T;
  description?: T;
  instructions?: T;
  scriptureReferences?:
    | T
    | {
        reference?: T;
        translation?: T;
        id?: T;
      };
  theologicalReflection?: T;
  suggestedJournalPrompt?: T;
  requiresJournalEntry?: T;
  usedInPathways?: T;
  pathwaysPhases?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermon-series_select".
 */
export interface SermonSeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons-content_select".
 */
export interface SermonsContentSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pastor?: T;
  series?: T;
  scripture?: T;
  tags?: T;
  audio?: T;
  video?: T;
  slides?: T;
  transcript?: T;
  duration?: T;
  date?: T;
  campus?: T;
  notes?: T;
  recommended?: T;
  status?: T;
  seo?:
    | T
    | {
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devotionals_select".
 */
export interface DevotionalsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  scripture?: T;
  body?: T;
  reflectionPrompt?: T;
  author?: T;
  date?: T;
  formationPractices?: T;
  pathwaysPhases?: T;
  relatedResources?: T;
  visibility?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  tags?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  resourceType?: T;
  file?: T;
  externalUrl?: T;
  categories?: T;
  relatedCourses?: T;
  relatedPathwaysPhases?: T;
  relatedMinistries?: T;
  visibility?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  eventType?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  virtualLink?: T;
  facilitators?: T;
  spiritualFocus?: T;
  relatedPrayerRequests?: T;
  requiresSession?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  profile?: T;
  summary?: T;
  request?: T;
  visibility?: T;
  allowFollowUp?: T;
  status?: T;
  answerTestimony?: T;
  answeredAt?: T;
  relatedEvent?: T;
  assignedLeader?: T;
  followUpNotes?: T;
  followUpDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  priority?: T;
  audience?: T;
  relatedMinistries?: T;
  relatedCourse?: T;
  relatedPathwayPhase?: T;
  displayLocations?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notifications_select".
 */
export interface UserNotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  message?: T;
  notificationType?: T;
  announcement?: T;
  resource?: T;
  course?: T;
  pathwaysProgram?: T;
  pathwaysPhase?: T;
  enrollment?: T;
  credential?: T;
  read?: T;
  readAt?: T;
  deliveryChannels?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households_select".
 */
export interface HouseholdsSelect<T extends boolean = true> {
  name?: T;
  members?: T;
  primaryContact?: T;
  campus?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  leader?: T;
  teamMembers?: T;
  status?: T;
  meetingSchedule?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  donor?: T;
  amount?: T;
  fund?: T;
  method?: T;
  date?: T;
  reference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "giving-campaigns_select".
 */
export interface GivingCampaignsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  donations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  credentialType?: T;
  issuingBody?: T;
  requiredCourses?: T;
  requiredPathwaysProgram?: T;
  requiredPathwaysPhase?: T;
  requiredAssignments?: T;
  requiredAssessments?: T;
  minimumScore?: T;
  mentorApprovalRequired?: T;
  autoAward?: T;
  requiresPastorApproval?: T;
  certificateTemplate?: T;
  expires?: T;
  expirationMonths?: T;
  visibility?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  apiTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  contactEmail?: string | null;
  pathwaysDescription?: string | null;
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  contactEmail?: T;
  pathwaysDescription?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}