/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tags: Tag;
    media: Media;
    profiles: Profile;
    applications: Application;
    courses: Course;
    modules: Module;
    lessons: Lesson;
    assignments: Assignment;
    'assignment-types': AssignmentType;
    submissions: Submission;
    enrollments: Enrollment;
    'sermon-series': SermonSery;
    sermons: Sermon;
    'sermons-content': SermonsContent;
    devotionals: Devotional;
    'blog-posts': BlogPost;
    'api-keys': ApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    'assignment-types': AssignmentTypesSelect<false> | AssignmentTypesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'sermon-series': SermonSeriesSelect<false> | SermonSeriesSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    'sermons-content': SermonsContentSelect<false> | SermonsContentSelect<true>;
    devotionals: DevotionalsSelect<false> | DevotionalsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Auth0 user ID (e.g., auth0|123...)
   */
  auth0Id?: string | null;
  /**
   * Synced from Auth0 → email_verified
   */
  emailVerified?: boolean | null;
  roles: (
    | 'admin'
    | 'pastor'
    | 'leader'
    | 'instructor'
    | 'mentor'
    | 'staff'
    | 'volunteer'
    | 'member'
    | 'student'
    | 'viewer'
  )[];
  /**
   * Connect to user profile
   */
  profile?: (number | null) | Profile;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  displayName: string;
  /**
   * Auto or manually set profile slug.
   */
  slug?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  testimony?: string | null;
  pathwaysPhase?: ('restore' | 'root' | 'rise' | 'release' | 'alumni' | 'none') | null;
  pathwaysProgress?: number | null;
  ministryFocus?: string | null;
  volunteerInterests?:
    | ('hospitality' | 'worship' | 'creative' | 'outreach' | 'youth' | 'teaching' | 'prayer' | 'events')[]
    | null;
  spiritualGifts?:
    | (
        | 'teaching'
        | 'leadership'
        | 'wisdom'
        | 'prophecy'
        | 'healing'
        | 'encouragement'
        | 'service'
        | 'administration'
        | 'evangelism'
        | 'faith'
      )[]
    | null;
  skills?: string | null;
  discProfile?: ('d' | 'i' | 's' | 'c') | null;
  enneagram?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') | null;
  spiritualGiftAssessment?: string | null;
  badges?:
    | {
        title?: string | null;
        icon?: (number | null) | Media;
        earnedDate?: string | null;
        id?: string | null;
      }[]
    | null;
  isMentor?: boolean | null;
  leadershipTrackStatus?: ('none' | 'training' | 'serving' | 'leading') | null;
  leadershipNotes?: string | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    tiktok?: string | null;
    website?: string | null;
  };
  contactPreference?: ('email' | 'call' | 'text') | null;
  doNotContact?: boolean | null;
  user?: (number | null) | User;
  accountabilityPartner?: (number | null) | Profile;
  accountabilityNotes?: string | null;
  pastorOrMinistryLead?: (number | null) | Profile;
  leaderNotes?: string | null;
  enrollments?: (number | Enrollment)[] | null;
  /**
   * Ministry / leadership roles for this person.
   */
  roles?:
    | (
        | 'admin'
        | 'pastor'
        | 'leader'
        | 'instructor'
        | 'mentor'
        | 'staff'
        | 'volunteer'
        | 'member'
        | 'student'
        | 'viewer'
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Sermon;
    canonicalURL?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  visibility?: ('public' | 'private') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  course: number | Course;
  courseTitle?: string | null;
  profile: number | Profile;
  instructor?: (number | null) | Profile;
  mentor?: (number | null) | Profile;
  status?: ('enrolled' | 'in-progress' | 'completed' | 'withdrawn' | 'incomplete') | null;
  progress?: number | null;
  certificateIssued?: boolean | null;
  startDate: string;
  endDate?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug?: string | null;
  summary?: string | null;
  description?: string | null;
  courseType:
    | 'pathways-phase'
    | 'weekly-class'
    | 'workshop'
    | 'leadership-lab'
    | 'mentorship'
    | 'certification'
    | 'module';
  pathwaysPhase?: ('restore' | 'root' | 'rise' | 'release' | 'all' | 'none') | null;
  modules?: (number | Module)[] | null;
  instructors?: (number | Profile)[] | null;
  startDate?: string | null;
  endDate?: string | null;
  meetingDay?: string | null;
  meetingTime?: string | null;
  heroImage?: (number | null) | Media;
  isActive?: boolean | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  course: number | Course;
  order?: number | null;
  lessons?: (number | Lesson)[] | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  module: number | Module;
  order?: number | null;
  assignments?: (number | Assignment)[] | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: number;
  title: string;
  type?: (number | null) | AssignmentType;
  lesson: number | Lesson;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  scripture?: string | null;
  reading?: string | null;
  order?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignment-types".
 */
export interface AssignmentType {
  id: number;
  label: string;
  description?: string | null;
  requiresSubmission?: boolean | null;
  allowAttachments?: boolean | null;
  allowTextEntry?: boolean | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  fullName: string;
  preferredName?: string | null;
  dateOfBirth?: string | null;
  gender?: ('male' | 'female' | 'nonbinary' | 'prefer-not') | null;
  phone: string;
  email: string;
  address?: string | null;
  fwcMember?: ('yes' | 'attend' | 'interested' | 'other-church') | null;
  churchName?: string | null;
  previousPrograms?: ('yes' | 'no') | null;
  previousProgramsDescription?: string | null;
  phase: 'restore' | 'root' | 'rise' | 'release' | 'unsure';
  whyJoin?: string | null;
  spiritualGoals?: string | null;
  preferredMeetingTime: 'weeknights' | 'saturday' | 'sunday' | 'any';
  meetingFrequency: 'weekly' | 'biweekly' | 'monthly' | 'unsure';
  supportNeeds?: ('virtual' | 'accessibility' | 'other')[] | null;
  otherSupport?: string | null;
  agreement: boolean;
  signature: string;
  signatureDate: string;
  status: 'pending' | 'interview' | 'accepted' | 'waitlisted' | 'rejected';
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  profile: number | Profile;
  assignment: number | Assignment;
  lesson: number | Lesson;
  assignmentTitle?: string | null;
  textEntry?: string | null;
  attachments?: (number | Media)[] | null;
  status?: ('submitted' | 'reviewed' | 'revise' | 'passed' | 'failed') | null;
  grade?: string | null;
  feedback?: string | null;
  submittedAt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermon-series".
 */
export interface SermonSery {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Sermon;
  seo?: {
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Sermon;
      canonicalURL?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons-content".
 */
export interface SermonsContent {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Only users with the "pastor" role appear here.
   */
  pastor: number | User;
  series?: (number | null) | SermonSery;
  scripture?: string | null;
  tags?: (number | Tag)[] | null;
  audio?: (number | null) | Sermon;
  video?: (number | null) | Sermon;
  slides?: (number | null) | Sermon;
  transcript?: (number | null) | Sermon;
  duration?: string | null;
  date: string;
  campus: 'clarksville' | 'murfreesboro' | 'nashville' | 'online';
  /**
   * Upload sermon notes (PDF, DOCX, images, etc.)
   */
  notes?: (number | null) | Sermon;
  /**
   * Recommended sermons to show after watching.
   */
  recommended?: (number | SermonsContent)[] | null;
  status?: ('draft' | 'review' | 'published') | null;
  seo?: {
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Sermon;
      canonicalURL?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devotionals".
 */
export interface Devotional {
  id: number;
  title: string;
  slug?: string | null;
  scripture?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  date: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Sermon;
    canonicalURL?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug?: string | null;
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Sermon;
    canonicalURL?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  label: string;
  key: string;
  apiTags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'assignments';
        value: number | Assignment;
      } | null)
    | ({
        relationTo: 'assignment-types';
        value: number | AssignmentType;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'sermon-series';
        value: number | SermonSery;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'sermons-content';
        value: number | SermonsContent;
      } | null)
    | ({
        relationTo: 'devotionals';
        value: number | Devotional;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  auth0Id?: T;
  emailVerified?: T;
  roles?: T;
  profile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  avatar?: T;
  bio?: T;
  testimony?: T;
  pathwaysPhase?: T;
  pathwaysProgress?: T;
  ministryFocus?: T;
  volunteerInterests?: T;
  spiritualGifts?: T;
  skills?: T;
  discProfile?: T;
  enneagram?: T;
  spiritualGiftAssessment?: T;
  badges?:
    | T
    | {
        title?: T;
        icon?: T;
        earnedDate?: T;
        id?: T;
      };
  isMentor?: T;
  leadershipTrackStatus?: T;
  leadershipNotes?: T;
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        tiktok?: T;
        website?: T;
      };
  contactPreference?: T;
  doNotContact?: T;
  user?: T;
  accountabilityPartner?: T;
  accountabilityNotes?: T;
  pastorOrMinistryLead?: T;
  leaderNotes?: T;
  enrollments?: T;
  roles?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  preferredName?: T;
  dateOfBirth?: T;
  gender?: T;
  phone?: T;
  email?: T;
  address?: T;
  fwcMember?: T;
  churchName?: T;
  previousPrograms?: T;
  previousProgramsDescription?: T;
  phase?: T;
  whyJoin?: T;
  spiritualGoals?: T;
  preferredMeetingTime?: T;
  meetingFrequency?: T;
  supportNeeds?: T;
  otherSupport?: T;
  agreement?: T;
  signature?: T;
  signatureDate?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  courseType?: T;
  pathwaysPhase?: T;
  modules?: T;
  instructors?: T;
  startDate?: T;
  endDate?: T;
  meetingDay?: T;
  meetingTime?: T;
  heroImage?: T;
  isActive?: T;
  featured?: T;
  publishedAt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  course?: T;
  order?: T;
  lessons?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  module?: T;
  order?: T;
  assignments?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  lesson?: T;
  instructions?: T;
  scripture?: T;
  reading?: T;
  order?: T;
  metadata?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignment-types_select".
 */
export interface AssignmentTypesSelect<T extends boolean = true> {
  label?: T;
  description?: T;
  requiresSubmission?: T;
  allowAttachments?: T;
  allowTextEntry?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  profile?: T;
  assignment?: T;
  lesson?: T;
  assignmentTitle?: T;
  textEntry?: T;
  attachments?: T;
  status?: T;
  grade?: T;
  feedback?: T;
  submittedAt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  course?: T;
  courseTitle?: T;
  profile?: T;
  instructor?: T;
  mentor?: T;
  status?: T;
  progress?: T;
  certificateIssued?: T;
  startDate?: T;
  endDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermon-series_select".
 */
export interface SermonSeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons-content_select".
 */
export interface SermonsContentSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pastor?: T;
  series?: T;
  scripture?: T;
  tags?: T;
  audio?: T;
  video?: T;
  slides?: T;
  transcript?: T;
  duration?: T;
  date?: T;
  campus?: T;
  notes?: T;
  recommended?: T;
  status?: T;
  seo?:
    | T
    | {
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devotionals_select".
 */
export interface DevotionalsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  scripture?: T;
  body?: T;
  author?: T;
  date?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  tags?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  apiTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  contactEmail?: string | null;
  pathwaysDescription?: string | null;
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  contactEmail?: T;
  pathwaysDescription?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}